/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyGui;

import LectoresDeArchivos.GraphvizHelper;
import LectoresDeArchivos.SimpleList;
import desktopappcolineairport.DesktopAppColineAirport;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author javier
 */
public class JPanelReportes extends javax.swing.JPanel {

    private static final String NOMBRE_ARBOL = "BTree";
    private static final String NOMBRE_MATRIX = "MatrixRuta";
    private static final String NOMBRE_HASH = "HashTableReserva";
    private static final String NOMBRE_MAPA = "Mapa";
    /**
     * Creates new form JPanelDestino
     */
    public JPanelReportes() {
        System.out.println("Destino");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDestinos = new javax.swing.JButton();
        btnRutas = new javax.swing.JButton();
        btnReservas = new javax.swing.JButton();
        btnMapa = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();

        btnDestinos.setText("Destinos");
        btnDestinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestinosActionPerformed(evt);
            }
        });

        btnRutas.setText("Rutas");
        btnRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutasActionPerformed(evt);
            }
        });

        btnReservas.setText("Reservas");
        btnReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasActionPerformed(evt);
            }
        });

        btnMapa.setText("Mapa");
        btnMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapaActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDestinos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnRefresh)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnDestinos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRutas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReservas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMapa)
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        
        SimpleList<String> graphvizDestinos = new SimpleList<String>(DesktopAppColineAirport.getDotDestinos());
        SimpleList<String> graphvizRutas = new SimpleList<String>(DesktopAppColineAirport.getDotRutas());
        SimpleList<String> graphvizReservas = new SimpleList<String>(DesktopAppColineAirport.getDotReservas());
        SimpleList<String> graphvizMapa = new SimpleList<String>(DesktopAppColineAirport.getDotMapa());
        
        GraphvizHelper.draw(graphvizDestinos, NOMBRE_ARBOL);
        GraphvizHelper.draw(graphvizRutas, NOMBRE_MATRIX);
        GraphvizHelper.draw(graphvizReservas, NOMBRE_HASH);
        GraphvizHelper.draw(graphvizMapa, NOMBRE_MAPA);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasActionPerformed
        try {
            Runtime.getRuntime().exec("nohup display " + GraphvizHelper.DIR_IMG + NOMBRE_HASH +  ".png &");
        } catch (IOException ex) {
            Logger.getLogger(GraphvizHelper.class.getName()).log(Level.SEVERE, null, ex);
        }
        //La pone el jpanel
    }//GEN-LAST:event_btnReservasActionPerformed

    private void btnDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestinosActionPerformed
        try {
            Runtime.getRuntime().exec("nohup display " + GraphvizHelper.DIR_IMG + NOMBRE_ARBOL +  ".png &");
        } catch (IOException ex) {
            Logger.getLogger(GraphvizHelper.class.getName()).log(Level.SEVERE, null, ex);
        }
        //La pone el jpanel
    }//GEN-LAST:event_btnDestinosActionPerformed

    private void btnRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutasActionPerformed
        try {
            Runtime.getRuntime().exec("nohup display " + GraphvizHelper.DIR_IMG + NOMBRE_MATRIX +  ".png &");
        } catch (IOException ex) {
            Logger.getLogger(GraphvizHelper.class.getName()).log(Level.SEVERE, null, ex);
        }
        //La pone el jpanel
    }//GEN-LAST:event_btnRutasActionPerformed

    private void btnMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapaActionPerformed
        try {
            Runtime.getRuntime().exec("nohup display " + GraphvizHelper.DIR_IMG + NOMBRE_MAPA +  ".png &");
        } catch (IOException ex) {
            Logger.getLogger(GraphvizHelper.class.getName()).log(Level.SEVERE, null, ex);
        }
        //La pone el jpanel
    }//GEN-LAST:event_btnMapaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDestinos;
    private javax.swing.JButton btnMapa;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReservas;
    private javax.swing.JButton btnRutas;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
